#!/bin/bash

echo "🧪 Testando Gemini CLI de dentro do projeto"
echo "PWD: $(pwd)"
echo ""
echo "Opções de teste:"
echo ""
echo "1️⃣ TESTE 1: Positional argument"
echo "   gemini \"Read briefing-test.txt and create the test file\""
echo ""
echo "2️⃣ TESTE 2: Via stdin"
echo "   cat briefing-test.txt | gemini"
echo ""
echo "3️⃣ TESTE 3: Com --yolo mode"
echo "   gemini --yolo \"Read briefing-test.txt and create the test file\""
echo ""
echo "4️⃣ TESTE 4: Com --approval-mode auto_edit"
echo "   gemini --approval-mode auto_edit \"Read briefing-test.txt and create the test file\""
echo ""
echo "Qual você quer testar?"
